CREATE TABLE IF NOT EXISTS `cn_province` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint DEFAULT NULL COMMENT '父节点id',
  `parent_path` json DEFAULT NULL COMMENT '父节点路径id',
  `level_type` smallint unsigned DEFAULT NULL COMMENT '等级类型 310省 320自治区 410直辖市 420特别行政区',
  `next_level_type` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '下级等级类型',
  `name_cn` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '中文名',
  `name_en` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '英文名',
  `name_other` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其他语言名',
  `name_pinyin` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '拼音 - 全拼',
  `name_jianpin` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '拼音 - 简拼',
  `region_code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '行政区代码、邮编',
  `phone_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '手机号区号',
  `zone` tinyint(1) DEFAULT NULL COMMENT '区域 1北半球国家、北方城市 2南半球国家、南半球城市',
  `utc` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '时区',
  `lng` double DEFAULT NULL COMMENT '经度',
  `lat` double DEFAULT NULL COMMENT '维度',
  `capital` tinyint(1) DEFAULT '0' COMMENT '是否是首都、省会',
  `osm_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'openstreetmap id',
  `geo_names_id` int DEFAULT NULL COMMENT 'geonames id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_province_name_cn` (`parent_id`,`name_cn`) USING BTREE,
  KEY `idx_province_name_en` (`parent_id`,`name_en`) USING BTREE,
  KEY `idx_province_name_other` (`parent_id`,`name_other`) USING BTREE,
  KEY `idx_province_name_pinyin` (`parent_id`,`name_pinyin`) USING BTREE,
  KEY `idx_province_name_jianpin` (`parent_id`,`name_jianpin`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=28309509700050218 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='中国 - 300 - 省级（310省 320自治区 410直辖市 420特别行政区）';

INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (110000, 296, '[1, 296]', 410, 'cn_600', '北京市', 'Beijing', '北京', 'BeiJingShi', 'BJS', '100000', '010', 1, NULL, 116.405285, 39.904989, 1, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (120000, 296, '[1, 296]', 410, 'cn_600', '天津市', 'Tianjin', '天津', 'TianJinShi', 'TJS', '300000', '022', 1, NULL, 117.190182, 39.125596, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (130000, 296, '[1, 296]', 310, 'cn_500', '河北省', 'Hebei', '河北', 'HeBeiSheng', 'HBS', NULL, NULL, 1, NULL, 114.502461, 38.045474, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (140000, 296, '[1, 296]', 310, 'cn_500', '山西省', 'Shanxi', '山西', 'ShanXiSheng', 'SXS', NULL, NULL, 1, NULL, 112.549248, 37.857014, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (150000, 296, '[1, 296]', 320, 'cn_500', '内蒙古自治区', 'Neimenggu', '内蒙古', 'NeiMengGuZiZhiQu', 'NMGZZQ', NULL, NULL, 1, NULL, 111.670801, 40.818311, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (210000, 296, '[1, 296]', 310, 'cn_500', '辽宁省', 'Liaoning', '辽宁', 'LiaoNingSheng', 'LNS', NULL, NULL, 1, NULL, 123.429096, 41.796767, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (220000, 296, '[1, 296]', 310, 'cn_500', '吉林省', 'Jilin', '吉林', 'JiLinSheng', 'JLS', NULL, NULL, 1, NULL, 125.3245, 43.886841, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (230000, 296, '[1, 296]', 310, 'cn_500', '黑龙江省', 'Heilongjiang', '黑龙江', 'HeiLongJiangSheng', 'HLJS', NULL, NULL, 1, NULL, 126.642464, 45.756967, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (310000, 296, '[1, 296]', 410, 'cn_600', '上海市', 'Shanghai', '上海', 'ShangHaiShi', 'SHS', '200000', '021', 2, NULL, 121.472644, 31.231706, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (320000, 296, '[1, 296]', 310, 'cn_500', '江苏省', 'Jiangsu', '江苏', 'JiangSuSheng', 'JSS', NULL, NULL, 2, NULL, 118.767413, 32.041544, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (330000, 296, '[1, 296]', 310, 'cn_500', '浙江省', 'Zhejiang', '浙江', 'ZheJiangSheng', 'ZJS', NULL, NULL, 2, NULL, 120.153576, 30.287459, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (340000, 296, '[1, 296]', 310, 'cn_500', '安徽省', 'Anhui', '安徽', 'AnHuiSheng', 'AHS', NULL, NULL, 2, NULL, 117.283042, 31.86119, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (350000, 296, '[1, 296]', 310, 'cn_500', '福建省', 'Fujian', '福建', 'FuJianSheng', 'FJS', NULL, NULL, 2, NULL, 119.306239, 26.075302, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (360000, 296, '[1, 296]', 310, 'cn_500', '江西省', 'Jiangxi', '江西', 'JiangXiSheng', 'JXS', NULL, NULL, 2, NULL, 115.892151, 28.676493, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (370000, 296, '[1, 296]', 310, 'cn_500', '山东省', 'Shandong', '山东', 'ShanDongSheng', 'SDS', NULL, NULL, 1, NULL, 117.000923, 36.675807, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (410000, 296, '[1, 296]', 310, 'cn_500', '河南省', 'Henan', '河南', 'HeNanSheng', 'HNS', NULL, NULL, 1, NULL, 113.665412, 34.757975, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (420000, 296, '[1, 296]', 310, 'cn_500', '湖北省', 'Hubei', '湖北', 'HuBeiSheng', 'HBS', NULL, NULL, 2, NULL, 114.298572, 30.584355, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (430000, 296, '[1, 296]', 310, 'cn_500', '湖南省', 'Hunan', '湖南', 'HuNanSheng', 'HNS', NULL, NULL, 2, NULL, 112.982279, 28.19409, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (440000, 296, '[1, 296]', 310, 'cn_500', '广东省', 'Guangdong', '广东', 'GuangDongSheng', 'GDS', NULL, NULL, 2, NULL, 113.280637, 23.125178, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (450000, 296, '[1, 296]', 320, 'cn_500', '广西壮族自治区', 'Guangxi', '广西', 'GuangXiZhuangZuZiZhiQu', 'GXZZZZQ', NULL, NULL, 2, NULL, 108.320004, 22.82402, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (460000, 296, '[1, 296]', 310, 'cn_500', '海南省', 'Hainan', '海南', 'HaiNanSheng', 'HNS', NULL, NULL, 2, NULL, 110.33119, 20.031971, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (500000, 296, '[1, 296]', 410, 'cn_600', '重庆市', 'Chongqing', '重庆', 'ChongQingShi', 'CQS', '400000', '023', 2, NULL, 106.504962, 29.533155, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (510000, 296, '[1, 296]', 310, 'cn_500', '四川省', 'Sichuan', '四川', 'SiChuanSheng', 'SCS', NULL, NULL, 2, NULL, 104.065735, 30.659462, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (520000, 296, '[1, 296]', 310, 'cn_500', '贵州省', 'Guizhou', '贵州', 'GuiZhouSheng', 'GZS', NULL, NULL, 2, NULL, 106.713478, 26.578343, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (530000, 296, '[1, 296]', 310, 'cn_500', '云南省', 'Yunnan', '云南', 'YunNanSheng', 'YNS', NULL, NULL, 2, NULL, 102.712251, 25.040609, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (540000, 296, '[1, 296]', 320, 'cn_500', '西藏自治区', 'Xizang', '西藏', 'XiZangZiZhiQu', 'XZZZQ', NULL, NULL, 2, NULL, 91.132212, 29.660361, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (610000, 296, '[1, 296]', 310, 'cn_500', '陕西省', 'Shaanxi', '陕西', 'ShanXiSheng', 'SXS', NULL, NULL, 1, NULL, 108.948024, 34.263161, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (620000, 296, '[1, 296]', 310, 'cn_500', '甘肃省', 'Gansu', '甘肃', 'GanSuSheng', 'GSS', NULL, NULL, 1, NULL, 103.823557, 36.058039, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (630000, 296, '[1, 296]', 310, 'cn_500', '青海省', 'Qinghai', '青海', 'QingHaiSheng', 'QHS', NULL, NULL, 1, NULL, 101.778916, 36.623178, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (640000, 296, '[1, 296]', 320, 'cn_500', '宁夏回族自治区', 'Ningxia', '宁夏', 'NingXiaHuiZuZiZhiQu', 'NXHZZZQ', NULL, NULL, 1, NULL, 106.278179, 38.46637, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (650000, 296, '[1, 296]', 320, 'cn_500', '新疆维吾尔自治区', 'Xinjiang', '新疆', 'XinJiangWeiWuErZiZhiQu', 'XJWWEZZQ', NULL, NULL, 1, NULL, 87.617733, 43.792818, 0, NULL, NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (710000, 296, '[1, 296]', 310, 'cn_500', '台湾省', 'Taiwan', '台湾', 'TaiWanSheng', 'TWS', NULL, NULL, 2, NULL, 121, 24, 0, '3777248', NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (810000, 296, '[1, 296]', 420, 'cn_600', '香港', 'Hong Kong', '香港', 'XiangGang', 'XG', '999077', '852', 2, NULL, 114.12, 22.26, 0, '913110', NULL);
INSERT INTO `cn_province` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `capital`, `osm_id`, `geo_names_id`) VALUES (820000, 296, '[1, 296]', 420, 'cn_600', '澳门', 'Macao', '澳门', 'AoMen', 'AM', '999078', '853', 2, NULL, 113.5, 22.2, 0, '1867188', NULL);
