CREATE TABLE IF NOT EXISTS `country` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint DEFAULT NULL COMMENT '父节点id',
  `parent_path` json DEFAULT NULL COMMENT '父节点路径id',
  `level_type` smallint DEFAULT NULL COMMENT '等级类型 210国家',
  `next_level_type` char(6) DEFAULT NULL COMMENT '下级等级类型',
  `name_cn` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '中文名',
  `name_en` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '英文名',
  `name_other` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其他语言名',
  `name_pinyin` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '拼音-全拼',
  `name_jianpin` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '拼音-简拼',
  `region_code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '行政区代码、邮编',
  `phone_code` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '手机号区号',
  `zone` tinyint(1) DEFAULT NULL COMMENT '所属区域 1北半球国家、北方城市 2南半球国家、南半球城市',
  `utc` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '时区',
  `lng` double DEFAULT NULL COMMENT '经度',
  `lat` double DEFAULT NULL COMMENT '维度',
  `osm_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'openstreetmap id',
  `geo_names_id` int DEFAULT NULL COMMENT 'geonames id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_country_name_cn` (`parent_id`,`name_cn`) USING BTREE,
  KEY `idx_country_name_en` (`parent_id`,`name_en`) USING BTREE,
  KEY `idx_country_name_other` (`parent_id`,`name_other`) USING BTREE,
  KEY `idx_country_name_pinyin` (`parent_id`,`name_pinyin`) USING BTREE,
  KEY `idx_country_name_jianpin` (`parent_id`,`name_jianpin`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=28309509700050218 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='200 - 国家210';

INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (100, 2, '[2]', 210, 'ot_300', '阿尔巴尼亚', 'Albania', 'AL', 'AErBaNiYa', 'AEBNY', 'ALB', '355', 1, '+1', 41.18, 19.49, '53292', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (101, 5, '[5]', 210, 'ot_300', '阿尔及利亚', 'Algeria', 'DZ', 'AErJiLiYa', 'AEJLY', 'DZA', '213', 1, '+1', 36.42, 3.08, '192756', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (102, 1, '[1]', 210, 'ot_300', '阿富汗', 'Afghanistan', 'AF', 'AFuHan', 'AFH', 'AFG', '93', 1, '+5', 34.28, 69.11, '303427', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (103, 4, '[4]', 210, 'ot_300', '阿根廷', 'Argentina', 'AR', 'AGenTing', 'AGT', 'ARG', '54', 2, '-3', -36.3, -60, '286393', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (104, 2, '[2]', 210, 'ot_500', '爱尔兰', 'Ireland', 'IE', 'AiErLan', 'AEL', 'IRL', '353', 1, '+0', 53.21, -6.15, '62273', 2963597);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (105, 5, '[5]', 210, 'ot_500', '埃及', 'Egypt', 'EG', 'AiJi', 'AJ', 'EGY', '20', 1, '+2', 30.01, 31.14, '1473947', 357994);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (106, 5, '[5]', 210, 'ot_300', '埃塞俄比亚', 'Ethiopia', 'ET', 'AiSaiEBiYa', 'ASEBY', 'ETH', '251', 2, '+3', 9.02, 38.42, '192800', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (107, 2, '[2]', 210, 'ot_600', '爱沙尼亚', 'Estonia', 'EE', 'AiShaNiYa', 'ASNY', 'EST', '372', 1, '+2', 59.22, 24.48, '79510', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (108, 1, '[1]', 210, 'ot_300', '阿拉伯联合酋长国', 'The United Arab Emirates', 'AE', 'ALaBaiLianHeQiuZhangGuo', 'ALBLHQZG', 'ARE', '971', 1, '+4', 24.0002488, 53.9994829, '307763', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (109, 1, '[1]', 210, 'ot_300', '阿曼', 'Oman', 'OM', 'AMan', 'AM', 'OMN', '968', 1, '+4', 23.37, 58.36, '305138', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (110, 2, '[2]', 210, 'ot_600', '安道尔', 'Andorra', 'AD', 'AnDaoEr', 'ADE', 'AND', '376', 1, '+1', 1.31, 42.3, '9407', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (111, 5, '[5]', 210, 'ot_300', '安哥拉', 'Angola', 'AO', 'AnGeLa', 'AGL', 'AGO', '244', 2, '+1', -8.5, 13.15, '195267', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (112, 3, '[3]', 210, 'ot_300', '安提瓜和巴布达', 'Antigua and Barbuda', 'AG', 'AnTiGuaHeBaBuDa', 'ATGHBBD', 'ATG', '1268', 2, '-4', 17.2, -61.48, '536900', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (113, 6, '[6]', 210, 'ot_300', '澳大利亚', 'Australia', 'AU', 'AoDaLiYa', 'ADLY', 'AUS', '61', 2, '+8', -35.15, 149.08, '80500', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (114, 2, '[2]', 210, 'ot_300', '奥地利', 'Austria', 'AT', 'AoDiLi', 'ADL', 'AUT', '43', 1, '+1', 48.12, 16.22, '16239', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (115, 1, '[1]', 210, 'ot_300', '阿塞拜疆', 'Azerbaijan', 'AZ', 'ASaiBaiJiang', 'ASBJ', 'AZE', '994', 1, '+4', 40.29, 49.56, '364110', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (116, 3, '[3]', 210, 'ot_600', '巴巴多斯', 'Barbados', 'BB', 'BaBaDuoSi', 'BBDS', 'BRB', '1246', 2, '-4', 13.05, -59.3, '547511', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (117, 6, '[6]', 210, 'ot_300', '巴布亚新几内亚', 'Papua New Guinea', 'PG', 'BaBuYaXinJiNeiYa', 'BBYXJNY', 'PNG', '675', 2, '+10', -9.24, 147.08, '307866', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (118, 3, '[3]', 210, 'ot_700', '巴哈马', 'Bahamas', 'BS', 'BaHaMa', 'BHM', 'BHS', '1242', 2, '-5', 25.05, -77.2, '547469', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (119, 2, '[2]', 210, 'ot_300', '白俄罗斯', 'Belarus', 'BY', 'BaiELuoSi', 'BELS', 'BLR', '375', 1, '+2', 53.52, 27.3, '59065', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (120, 1, '[1]', 210, 'ot_300', '巴基斯坦', 'Pakistan', 'PK', 'BaJiSiTan', 'BJST', 'PAK', '92', 1, '+5', 33.4, 73.1, '307573', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (121, 4, '[4]', 210, 'ot_700', '巴拉圭', 'Paraguay', 'PY', 'BaLaGui', 'BLG', 'PRY', '595', 2, '-4', -25.1, -57.3, '287077', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (122, 1, '[1]', 210, 'ot_500', '巴勒斯坦', 'State of Palestine', 'PS', 'BaLeSiTan', 'BLST', 'PLE', '970', 1, '+2', 30.8760272, 35.0015196, '1703814', 6254930);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (123, 1, '[1]', 210, 'ot_300', '巴林', 'Bahrain', 'BH', 'BaLin', 'BL', 'BHR', '973', 1, '+3', 26.1, 50.3, '378734', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (124, 3, '[3]', 210, 'ot_300', '巴拿马', 'Panama', 'PA', 'BaNaMa', 'BNM', 'PAN', '507', 2, '-5', 9, -79.25, '287668', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (125, 2, '[2]', 210, 'ot_600', '保加利亚', 'Bulgaria', 'BG', 'BaoJiaLiYa', 'BJLY', 'BGR', '359', 1, '+2', 42.45, 23.2, '186382', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (126, 4, '[4]', 210, 'ot_500', '巴西', 'Brazil', 'BR', 'BaXi', 'BX', 'BRA', '55', 2, '-3', -15.47, -47.55, '59470', 3469034);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (127, 2, '[2]', 210, 'ot_300', '北马其顿', 'North Macedonia', 'MK', 'BeiMaQiDun', 'BMQD', 'MKD', '389', 1, '+1', 42.00182, 21.4425, '53293', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (128, 5, '[5]', 210, 'ot_300', '贝宁', 'Benin', 'BJ', 'BeiNing', 'BN', 'BEN', '229', 2, '+1', 6.23, 2.42, '192784', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (129, 2, '[2]', 210, 'ot_300', '比利时', 'Belgium', 'BE', 'BiLiShi', 'BLS', 'BEL', '32', 1, '+1', 50.51, 4.21, '52411', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (130, 2, '[2]', 210, 'ot_500', '冰岛', 'Iceland', 'IS', 'BingDao', 'BD', 'ISL', '354', 2, '+0', 64.1, -21.57, '299133', 2629691);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (131, 5, '[5]', 210, 'ot_300', '博茨瓦纳', 'Botswana', 'BW', 'BoCiWaNa', 'BCWN', 'BWA', '267', 2, '+2', -24.45, 25.57, '1889339', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (132, 2, '[2]', 210, 'ot_300', '波兰', 'Poland', 'PL', 'BoLan', 'BL', 'POL', '48', 1, '+1', 52.13, 21, '49715', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (133, 4, '[4]', 210, 'ot_300', '玻利维亚', 'Bolivia', 'BO', 'BoLiWeiYa', 'BLWY', 'BOL', '591', 2, '-4', -16.2, -68.1, '252645', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (134, 3, '[3]', 210, 'ot_300', '伯利兹', 'Belize', 'BZ', 'BaiLiZi', 'BLZ', 'BLZ', '501', 2, '-6', 17.18, -88.3, '287827', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (135, 2, '[2]', 210, 'ot_300', '波斯尼亚和黑塞哥维那', 'Bosnia and Herzegovina', 'BA', 'BoSiNiYaHeHeiSaiGeWeiNa', 'BSNYHHSGWN', 'BIH', '387', 1, '+1', 43.85002, 18.37875, '2528142', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (136, 2, '[2]', 210, 'ot_600', '葡萄牙', 'The Portuguese Republic', 'PT', 'PuTaoYa', 'PTY', 'PRT', '351', 1, '+1', 38.42, -9.1, '295480', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (137, 1, '[1]', 210, 'ot_300', '不丹', 'Kingdom Of Bhutan', 'BT', 'BuDan', 'BD', 'BTN', '975', 2, '+6', 27.28, 89.38, '184629', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (138, 5, '[5]', 210, 'ot_300', '布基纳法索', 'Burkina Faso', 'BF', 'BuJiNaFaSuo', 'BJNFS', 'BFA', '226', 2, '+0', 12.15, -1.3, '192783', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (139, 5, '[5]', 210, 'ot_300', '布隆迪', 'Burundi', 'BI', 'BuLongDi', 'BLD', 'BDI', '257', 2, '+2', -3.16, 29.18, '195269', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (140, 1, '[1]', 210, 'ot_300', '朝鲜', 'Korea', 'KP', 'ChaoXian', 'CX', 'PRK', '850', 1, '+9', 39.09, 125.3, '192734', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (141, 5, '[5]', 210, 'ot_300', '赤道几内亚', 'Equatorial Guinea', 'GQ', 'ChiDaoJiNeiYa', 'CDJNY', 'GNQ', '240', 2, '+1', 3.45, 8.48, '192791', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (142, 2, '[2]', 210, 'ot_500', '丹麦', 'Denmark', 'DK', 'DanMai', 'DM', 'DNK', '45', 1, '+1', 55.41, 12.34, '50046', 2623032);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (143, 2, '[2]', 210, 'ot_300', '德国', 'Germany', 'DE', 'DeGuo', 'DG', 'DEU', '49', 1, '+1', 52.3, 13.25, '51477', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (144, 1, '[1]', 210, 'ot_500', '东帝汶', 'East Timor', 'TL', 'DongDiWen', 'DDW', 'TLS', '670', 2, '+9', 8.35, 125.35, '305142', 1966436);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (145, 2, '[2]', 210, 'ot_300', '瑞典', 'Sweden', 'SE', 'RuiDian', 'RD', 'SWE', '46', 1, '+1', 59.2, 18.03, '52822', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (146, 5, '[5]', 210, 'ot_300', '多哥', 'Togo', 'TG', 'DuoGe', 'DG', 'TGO', '228', 2, '+0', 6.09, 1.2, '192782', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (147, 3, '[3]', 210, 'ot_500', '多米尼加共和国', 'Republic', 'DO', 'DuoMiNiJiaGongHeGuo', 'DMNJGHG', 'DOM', '1890', 2, '-4', 18.3, -69.59, '307828', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (148, 3, '[3]', 210, 'ot_300', '多米尼克', 'Dominica', 'DM', 'DuoMiNiKe', 'DMNK', 'DMA', '1767', 2, '-4', -61.23, -15.18, '307823', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (149, 4, '[4]', 210, 'ot_300', '厄瓜多尔', 'Ecuador', 'EC', 'EGuaDuoEr', 'EGDE', 'ECU', '593', 2, '-5', -0.15, -78.35, '108089', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (150, 5, '[5]', 210, 'ot_500', '厄立特里亚', 'Eritrea', 'ER', 'ELiTeLiYa', 'ELTLY', 'ERI', '291', 2, '+3', 15.3251, 38.93137, '296961', 338010);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (151, 2, '[2]', 210, 'ot_300', '俄罗斯', 'Russia', 'RU', 'ELuoSi', 'ELS', 'RUS', '7', 1, '+3', 55.45, 37.35, '60189', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (152, 2, '[2]', 210, 'ot_300', '法国', 'French Republi', 'FR', 'FaGuo', 'FG', 'FRA', '33', 1, '+1', 48.5, 2.2, '11741663', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (153, 2, '[2]', 210, 'ot_300', '梵蒂冈', 'Vatican City State', 'VA', 'FanDiGang', 'FDG', 'VAT', '379', 1, '+1', 41.54, 12.27, '36989', 3164670);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (154, 6, '[6]', 210, 'ot_300', '斐济', 'Fiji', 'FJ', 'FeiJi', 'FJ', 'FJI', '679', 2, '+12', -18.06, 178.3, '571747', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (155, 1, '[1]', 210, 'ot_500', '菲律宾', 'Philippines', 'PH', 'FeiLüBin', 'FLB', 'PHL', '63', 2, '+8', 14.4, 121.03, '443174', 1694008);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (156, 2, '[2]', 210, 'ot_600', '芬兰', 'Finland', 'FI', 'FenLan', 'FL', 'FIN', '358', 1, '+2', 60.15, 25.03, '54224', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (157, 5, '[5]', 210, 'ot_500', '佛得角', 'Cabo Verde', 'CV', 'FoDeJiao', 'FDJ', 'CPV', '238', 2, '-1', 14.55, 23.31, '535774', 3374766);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (158, 5, '[5]', 210, 'ot_300', '冈比亚', 'Gambia', 'GM', 'GangBiYa', 'GBY', 'GMB', '220', 2, '+0', 13.28, -16.4, '192774', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (159, 5, '[5]', 210, 'ot_300', '刚果共和国', 'Republic of the Congo', 'CG', 'GangGuoGongHeGuo', 'GGGHG', 'COG', '242', 2, '+1', 15.14, 4.14, '192794', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (160, 5, '[5]', 210, 'ot_300', '刚果民主共和国', 'The Democratic Republic of the Congo', 'CD', 'GangGuoMinZhuGongHeGuo', 'GGMZGHG', 'COD', '242', 2, '+2', 15.18, 4.18, '192795', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (161, 1, '[1]', 210, 'ot_300', '格鲁吉亚', 'Georgia', 'GE', 'GeLuJiYa', 'GLJY', 'GEO', '995', 1, '+4', 41.43, 44.5, '28699', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (162, 4, '[4]', 210, 'ot_600', '哥伦比亚', 'Colombia', 'CO', 'GeLunBiYa', 'GLBY', 'COL', '57', 2, '-5', 4.34, -74, '120027', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (163, 3, '[3]', 210, 'ot_300', '哥斯达黎加', 'Costa Rica', 'CR', 'GeSiDaLiJia', 'GSDLJ', 'CRI', '506', 2, '-6', 9.55, -84.02, '287667', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (164, 3, '[3]', 210, 'ot_300', '古巴', 'Cuba', 'CU', 'GuBa', 'GB', 'CUB', '53', 2, '-5', 23.08, -82.22, '307833', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (165, 4, '[4]', 210, 'ot_300', '圭亚那', 'Guyana', 'GY', 'GuiYaNa', 'GYN', 'GUY', '592', 2, '-4', 6.5, -58.12, '287083', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (166, 3, '[3]', 210, 'ot_300', '海地', 'Haiti', 'HT', 'HaiDi', 'HD', 'HT', '509', 2, '-5', 18.4, -72.2, '307829', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (167, 1, '[1]', 210, 'ot_300', '韩国', 'Korea', 'KR', 'HanGuo', 'HG', 'KOR', '82', 1, '+9', 37.31, 126.58, '307756', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (168, 1, '[1]', 210, 'ot_300', '哈萨克斯坦', 'Kazakhstan', 'KZ', 'HaSaKeSiTan', 'HSKST', 'KAZ', '327', 1, '+3', 51.1, 71.3, '214665', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (169, 2, '[2]', 210, 'ot_600', '黑山', 'Montenegro', 'ME', 'HeiShan', 'HS', 'MNE', '382', 1, '+1', 41.41, 122.07, '53296', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (170, 2, '[2]', 210, 'ot_500', '荷兰', 'Netherlands', 'NL', 'HeLan', 'HL', 'NLD', '31', 1, '+1', 52.23, 4.54, '2323309', 2750405);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (171, 3, '[3]', 210, 'ot_600', '格林纳达', 'Grenada', 'GD', 'GeLinNaDa', 'GLND', 'GRD', '1809', 2, '-4', -61.44, -12.04, '550727', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (172, 3, '[3]', 210, 'ot_300', '洪都拉斯', 'Honduras', 'HN', 'HongDouLaSi', 'HDLS', 'HND', '504', 2, '-6', 14.05, -87.14, '287670', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (173, 5, '[5]', 210, 'ot_300', '加纳', 'Ghana', 'GH', 'JiaNa', 'JN', 'GHA', '233', 2, '+0', 5.35, -0.06, '192781', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (174, 3, '[3]', 210, 'ot_300', '加拿大', 'Canada', 'CA', 'JiaNaDa', 'JND', 'CAN', '1', 1, '-5', 45.27, -75.42, '1428125', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (175, 1, '[1]', 210, 'ot_300', '柬埔寨', 'Cambodia', 'KH', 'JianPuZhai', 'JPZ', 'KHM', '855', 2, '+7', 11.33, 104.55, '49898', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (176, 5, '[5]', 210, 'ot_300', '加蓬', 'Gabon', 'GA', 'JiaPeng', 'JP', 'GAB', '241', 2, '+1', 0.25, 9.26, '192793', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (177, 5, '[5]', 210, 'ot_500', '吉布提', 'Djibouti', 'DJ', 'JiBuTi', 'JBT', 'DJI', '253', 2, '+3', 11.08, 42.2, '192801', 223816);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (178, 2, '[2]', 210, 'ot_300', '捷克', 'Czech Republic', 'CZ', 'JieKe', 'JK', 'CZE', '420', 1, '+1', 14.25, 50.05, '51684', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (179, 1, '[1]', 210, 'ot_500', '吉尔吉斯斯坦', 'Kyrgyz Republic', 'KG', 'JiErJiSiSiTan', 'JEJSST', 'KGZ', '331', 1, '+6', 41.5089324, 74.724091, '178009', 1527747);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (180, 6, '[6]', 210, 'ot_700', '基里巴斯', 'Kiribati', 'KI', 'JiLiBaSi', 'JLBS', 'KIR', '686', 2, '+12', 1.3, 173, '571178', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (181, 5, '[5]', 210, 'ot_300', '津巴布韦', 'Zimbabwe', 'ZW', 'JinBaBuWei', 'JBBW', 'ZWE', '263', 2, '+2', -17.43, 31.02, '195272', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (182, 5, '[5]', 210, 'ot_300', '几内亚', 'Guinea', 'GN', 'JiNeiYa', 'JNY', 'GIN', '224', 2, '+0', 9.29, -13.49, '192778', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (183, 5, '[5]', 210, 'ot_300', '几内亚比绍', 'Guinea Bissau', 'GW', 'JiNeiYaBiShao', 'JNYBS', 'GNB', '245', 2, '+0', 11.52, 15.39, '192776', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (184, 5, '[5]', 210, 'ot_500', '喀麦隆', 'Cameroon', 'CM', 'KaMaiLong', 'KML', 'CMR', '237', 2, '+1', 3.5, 11.35, '192830', 2233387);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (185, 1, '[1]', 210, 'ot_300', '卡塔尔', 'Qatar', 'QA', 'KaTaEr', 'KTE', 'QAT', '974', 1, '+3', 25.15, 51.35, '305095', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (186, 2, '[2]', 210, 'ot_600', '克罗地亚', 'Croatia', 'HR', 'KeLuoDiYa', 'KLDY', 'HRV', '385', 1, '+1', 45.5, 15.58, '214885', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (187, 5, '[5]', 210, 'ot_500', '科摩罗', 'Union of Comoros', 'KM', 'KeMoLuo', 'KML', 'COM', '269', 2, '+3', 11.4, 43.19, '535790', 921929);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (188, 5, '[5]', 210, 'ot_500', '肯尼亚', 'Kenya', 'KE', 'KenNiYa', 'KNY', 'KEN', '254', 2, '+3', -1.17, 36.48, '192798', 192950);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (189, 5, '[5]', 210, 'ot_300', '科特迪瓦', 'Ivory Coast', 'CI', 'KeTeDiWa', 'KTDW', 'CIV', '225', 2, '+0', 6.51, 5.18, '192779', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (190, 1, '[1]', 210, 'ot_300', '科威特', 'Kuwait', 'KW', 'KeWeiTe', 'KWT', 'KWT', '965', 1, '+3', 29.3, 48, '305099', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (191, 6, '[6]', 210, 'ot_700', '库克群岛', 'Cook Islands', 'CK', 'KuKeQunDao', 'KKQD', 'COK', '682', 2, '-10', 24.6301555, -81.3762960679776, '2184233', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (192, 5, '[5]', 210, 'ot_500', '莱索托', 'Lesotho', 'LS', 'LaiSuoTuo', 'LST', 'LSO', '266', 2, '+2', -29.18, 27.3, '2093234', 932692);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (193, 1, '[1]', 210, 'ot_300', '老挝', 'Laos', 'LA', 'LaoWo', 'LW', 'LAO', '856', 2, '+7', 17.58, 102.36, '49903', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (194, 2, '[2]', 210, 'ot_300', '拉脱维亚', 'Latvia', 'LV', 'LaTuoWeiYa', 'LTWY', 'LVA', '371', 1, '+2', 56.53, 24.08, '72594', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (195, 1, '[1]', 210, 'ot_500', '黎巴嫩', 'Lebano', 'LB', 'LiBaNen', 'LBN', 'LBN', '961', 1, '+2', 33.53, 35.31, '184843', 272103);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (196, 5, '[5]', 210, 'ot_300', '利比里亚', 'Liberia', 'LR', 'LiBiLiYa', 'LBLY', 'LBR', '231', 2, '+0', 6.18, -10.47, '192780', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (197, 5, '[5]', 210, 'ot_300', '利比亚', 'Libya', 'LY', 'LiBiYa', 'LBY', 'LBY', '218', 2, '+2', 26.8234472, 18.1236723, '192758', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (198, 2, '[2]', 210, 'ot_300', '立陶宛', 'Lithuania', 'LT', 'LiTaoWan', 'LTW', 'LTU', '370', 1, '+2', 54.38, 25.19, '72596', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (199, 2, '[2]', 210, 'ot_500', '列支敦士登', 'Principality of Liechtenstein', 'LI', 'LieZhiDunShiDeng', 'LZDSD', 'LIE', '423', 1, '+1', 47.08, 9.31, '1155955', 3042058);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (200, 2, '[2]', 210, 'ot_500', '罗马尼亚', 'Romania', 'RO', 'LuoMaNiYa', 'LMNY', 'ROU', '40', 1, '+2', 44.27, 26.1, '90689', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (201, 2, '[2]', 210, 'ot_600', '卢森堡', 'Luxembourg', 'LU', 'LuSenBao', 'LSB', 'LUX', '352', 1, '+1', 49.37, 6.09, '2171347', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (202, 5, '[5]', 210, 'ot_500', '卢旺达', 'Rwanda', 'RW', 'LuWangDa', 'LWD', 'RWA', '250', 2, '+2', -1.95444, 30.06437, '171496', 49518);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (203, 5, '[5]', 210, 'ot_500', '马达加斯加', 'Madagascar', 'MG', 'MaDaJiaSiJia', 'MDJSJ', 'MDG', '261', 2, '+3', -18.55, 47.31, '447325', 1062947);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (204, 1, '[1]', 210, 'ot_500', '马尔代夫', 'Maldives', 'MV', 'MaErDaiFu', 'MEDF', 'MDV', '960', 2, '+5', 4, 73.28, '536773', 1282028);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (205, 2, '[2]', 210, 'ot_300', '马耳他', 'Malta', 'MT', 'MaErTa', 'MET', 'MLT', '356', 1, '+1', 35.54, 14.31, '365307', 2562770);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (206, 1, '[1]', 210, 'ot_300', '马来西亚', 'Malaysia', 'MY', 'MaLaiXiYa', 'MLXY', 'MYS', '60', 1, '+8', 3.09, 101.41, '2108121', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (207, 5, '[5]', 210, 'ot_500', '马拉维', 'Malawi', 'MW', 'MaLaWei', 'MLW', 'MWI', '265', 2, '+2', -14, 33.48, '195290', 927384);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (208, 5, '[5]', 210, 'ot_300', '马里', 'Mali', 'ML', 'MaLi', 'ML', 'MLI', '223', 2, '+0', 12.34, -7.55, '192785', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (209, 5, '[5]', 210, 'ot_300', '毛里求斯', 'Mauritius', 'MU', 'MaoLiQiuSi', 'MLQS', 'MUS', '230', 2, '+4', -20.2759451, 57.5703566, '535828', 934292);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (210, 5, '[5]', 210, 'ot_300', '毛里塔尼亚', 'Mauritania', 'MR', 'MaoLiTaNiYa', 'MLTNY', 'MRT', '222', 2, '+0', 18.09, 15.58, '192763', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (211, 6, '[6]', 210, 'ot_700', '马绍尔群岛', 'Marshall Island', 'MH', 'MaShaoErQunDao', 'MSEQD', 'MHL', '692', 2, '+12', 171.12, 7.09, '571771', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (212, 3, '[3]', 210, 'ot_300', '美国', 'United States of America', 'US', 'MeiGuo', 'MG', 'USA', '1', 1, '-5', 39.91, -77.02, '148838', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (213, 1, '[1]', 210, 'ot_500', '蒙古', 'Mongolia', 'MN', 'MengGu', 'MG', 'MNG', '976', 1, '+8', 46.8250388, 103.8499736, '161033', 2029969);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (214, 1, '[1]', 210, 'ot_300', '孟加拉国', 'Bangladesh', 'BD', 'MengJiaLaGuo', 'MJLG', 'BGD', '880', 2, '+6', 23.43, 90.26, '184640', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (215, 1, '[1]', 210, 'ot_300', '缅甸', 'Myanmar', 'MM', 'MianDian', 'MD', 'MMR', '95', 2, '+7', 16.45, 96.2, '50371', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (216, 6, '[6]', 210, 'ot_300', '密克罗尼西亚联邦', 'Federated States of Micronesia', 'FM', 'MiKeLuoNiXiYaLianBang', 'MKLNXYLB', 'FSM', '691', 1, '+10', 6.54, 158.09, '571802', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (217, 4, '[4]', 210, 'ot_600', '秘鲁', 'Peru', 'PE', 'BiLu', 'BL', 'PER', '51', 2, '-5', -12, -77, '288247', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (218, 2, '[2]', 210, 'ot_300', '摩尔多瓦', 'Moldova', 'MD', 'MoErDuoWa', 'MEDW', 'MDA', '373', 1, '+2', 28.5, -47, '58974', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (219, 5, '[5]', 210, 'ot_300', '摩洛哥', 'Morocco', 'MA', 'MoLuoGe', 'MLG', 'MAR', '212', 2, '+1', 31.1728205, -7.3362482, '3630439', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (220, 2, '[2]', 210, 'ot_700', '摩纳哥', 'Monaco', 'MC', 'MoNaGe', 'MNG', 'MCO', '377', 1, '+1', 7.25, -43.4, '1124039', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (221, 5, '[5]', 210, 'ot_300', '莫桑比克', 'Mozambique', 'MZ', 'MoSangBiKe', 'MSBK', 'MOZ', '258', 2, '+2', -25.58, 32.32, '195273', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (222, 3, '[3]', 210, 'ot_300', '墨西哥', 'Mexico', 'MX', 'MoXiGe', 'MXG', 'MEX', '52', 2, '-6', 19.2, -99.1, '114686', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (223, 5, '[5]', 210, 'ot_300', '纳米比亚', 'Namibia', 'NA', 'NaMiBiYa', 'NMBY', 'NAM', '264', 2, '+1', -22.35, 17.04, '195266', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (224, 5, '[5]', 210, 'ot_300', '南非', 'South Africa', 'ZA', 'NanFei', 'NF', 'ZAF', '27', 2, '+2', -28.8166236, 24.991639, '87565', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (225, 5, '[5]', 210, 'ot_300', '南苏丹', 'South Sudan', 'SS', 'NanSuDan', 'NSD', 'SSD', '211', 2, '+3', 4.51, 31.34, '1656678', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (226, 6, '[6]', 210, 'ot_600', '瑙鲁', 'Nauru', 'NR', 'NaoLu', 'NL', 'NRU', '674', 2, '+12', 166.55, 0.23, '571804', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (227, 1, '[1]', 210, 'ot_500', '尼泊尔', 'Nepal', 'NP', 'NiBoEr', 'NBE', 'NPL', '977', 2, '+5', 27.45, 85.2, '184633', 1282988);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (228, 3, '[3]', 210, 'ot_300', '尼加拉瓜', 'Nicaragua', 'NI', 'NiJiaLaGua', 'NJLG', 'NIC', '505', 2, '-6', 12.06, -86.2, '287666', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (229, 5, '[5]', 210, 'ot_300', '尼日尔', 'Niger', 'NE', 'NiRiEr', 'NRE', 'NER', '977', 2, '+1', 13.27, 2.06, '192786', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (230, 5, '[5]', 210, 'ot_300', '尼日利亚', 'Nigeria', 'NG', 'NiRiLiYa', 'NRLY', 'NGA', '234', 2, '+1', 9.05, 7.32, '192787', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (231, 6, '[6]', 210, 'ot_300', '纽埃', 'Niue', 'NU', 'NiuAi', 'NA', 'NIU', '683', 2, '-11', 169.55, 19.03, '1558556', 4036232);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (232, 2, '[2]', 210, 'ot_300', '挪威', 'Norway', 'NO', 'NuoWei', 'NW', 'NOR', '47', 1, '+1', 59.55, 10.45, '2978650', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (233, 6, '[6]', 210, 'ot_300', '帕劳', 'Republic Of Palau', 'PW', 'PaLao', 'PL', 'PLW', '680', 1, '+9', 7.2, 134.28, '571805', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (234, 1, '[1]', 210, 'ot_500', '日本', 'Japan', 'JP', 'RiBen', 'RB', 'JPN', '81', 1, '+9', 36.5748441, 139.2394179, '382313', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (235, 2, '[2]', 210, 'ot_300', '瑞士', 'Switzerland', 'CH', 'RuiShi', 'RS', 'CHE', '41', 1, '+1', 46.57, 7.28, '51701', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (236, 3, '[3]', 210, 'ot_300', '萨尔瓦多', 'Salvador', 'SV', 'SaErWaDuo', 'SEWD', 'SLV', '503', 2, '-6', 13.4, -89.1, '1520612', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (237, 5, '[5]', 210, 'ot_300', '塞尔维亚', 'Serbia', 'RS', 'SaiErWeiYa', 'SEWY', 'SRB', '381', 1, '+1', 44.79440266928538, 20.44043898582459, '1741311', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (238, 5, '[5]', 210, 'ot_300', '塞拉利昂', 'Sierra Leone', 'SL', 'SaiLaLiAng', 'SLLA', 'SLE', '232', 2, '+0', 8.3, -13.17, '192777', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (239, 5, '[5]', 210, 'ot_300', '塞内加尔', 'Senegal', 'SN', 'SaiNeiJiaEr', 'SNJE', 'SEN', '221', 2, '+0', 14.34, -17.29, '192775', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (240, 1, '[1]', 210, 'ot_500', '塞浦路斯', 'Cyprus', 'CY', 'SaiPuLuSi', 'SPLS', 'CYP', '357', 1, '+2', 35.1, 33.25, '307787', 146669);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (241, 5, '[5]', 210, 'ot_500', '塞舌尔', 'Seychelles', 'SC', 'SaiSheEr', 'SSE', 'SYC', '248', 2, '+4', -4.6574977, 55.4540146, '536765', 241170);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (242, 6, '[6]', 210, 'ot_500', '萨摩亚', 'San Marino', 'WS', 'SaMoYa', 'SMY', 'WSM', '685', 2, '+12', 43.9458623, 12.458306, '1872673', 4034894);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (243, 1, '[1]', 210, 'ot_500', '沙特阿拉伯', 'Saudi Arabia', 'SA', 'ShaTeALaBai', 'STALB', 'SAU', '966', 1, '+3', 24.41, 46.42, '307584', 102358);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (244, 5, '[5]', 210, 'ot_300', '圣多美和普林西比', 'Sao Tome And Principe', 'ST', 'ShengDuoMeiHePuLinXiBi', 'SDMHPLXB', 'STP', '239', 2, '+12', 0.1, 6.39, '535880', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (245, 3, '[3]', 210, 'ot_300', '圣卢西亚', 'Saint Lucia', 'LC', 'ShengLuXiYa', 'SLXY', 'LCA', '1758', 2, '-4', 14.02, -60.58, '550728', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (246, 2, '[2]', 210, 'ot_700', '圣马力诺', 'San Marino', 'SM', 'ShengMaLiNuo', 'SMLN', 'SMR', '378', 1, '+1', 43.56, 12.27, '54624', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (247, 3, '[3]', 210, 'ot_600', '圣文森特和格林纳丁斯', 'Saint Vincent', 'VC', 'ShengWenSenTeHeGeLinNaDingSi', 'SWSTHGLNDS', 'VCT', '1784', 2, '-4', -61.14, -13.12, '550725', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (248, 3, '[3]', 210, 'ot_300', '圣基茨和尼维斯', 'Saint Kitts And Nevis', 'KN', 'ShengJiCiHeNiWeiSi', 'SJCHNWS', 'KNA', '1869', 2, '-4', 17.17, -62.43, '536899', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (249, 1, '[1]', 210, 'ot_300', '斯里兰卡', 'Sri Lanka', 'LK', 'SiLiLanKa', 'SLLK', 'LKA', '94', 2, '+5:30', 7.5554942, 80.7137847, '536807', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (250, 2, '[2]', 210, 'ot_300', '斯洛伐克', 'Slovakia', 'SK', 'SiLuoFaKe', 'SLFK', 'SVK', '421', 1, '+1', 48.1, 17.07, '14296', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (251, 2, '[2]', 210, 'ot_700', '斯洛文尼亚', 'Slovenia', 'SI', 'SiLuoWenNiYa', 'SLWNY', 'SVN', '386', 1, '+1', 46.04, 14.33, '218657', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (252, 5, '[5]', 210, 'ot_500', '斯威士兰', 'Swaziland', 'SZ', 'SiWeiShiLan', 'SWSL', 'SWZ', '268', 2, '+2', -26.18, 31.06, '88210', 934841);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (253, 5, '[5]', 210, 'ot_300', '苏丹', 'Sudan', 'SD', 'SuDan', 'SD', 'SDN', '249', 2, '+2', 15.31, 32.35, '192789', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (254, 4, '[4]', 210, 'ot_300', '苏里南', 'Suriname', 'SR', 'SuLiNan', 'SLN', 'SUR', '597', 2, '-3', 5.5, -55.1, '287082', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (255, 6, '[6]', 210, 'ot_300', '所罗门群岛', 'SolomonIs', 'SB', 'SuoLuoMenQunDao', 'SLMQD', 'SLB', '677', 2, '+11', -9.27, 159.57, '1857436', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (256, 5, '[5]', 210, 'ot_300', '索马里', 'Somali', 'SO', 'SuoMaLi', 'SML', 'SOM', '252', 2, '+3', 2.02, 45.25, '192799', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (257, 1, '[1]', 210, 'ot_300', '泰国', 'Thailand', 'TH', 'TaiGuo', 'TG', 'THA', '66', 2, '+7', 13.45, 100.35, '2067731', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (258, 1, '[1]', 210, 'ot_300', '塔吉克斯坦', 'Tajikstan', 'TJ', 'TaJiKeSiTan', 'TJKST', 'TJK', '992', 1, '+5', 38.33, 68.48, '214626', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (259, 6, '[6]', 210, 'ot_500', '汤加', 'Tonga', 'TO', 'TangJia', 'TJ', 'TON', '676', 2, '+13', -21.1, -174, '2186665', 4032283);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (260, 5, '[5]', 210, 'ot_300', '坦桑尼亚', 'Tanzania', 'TZ', 'TanSangNiYa', 'TSNY', 'TZA', '255', 2, '+3', -6.08, 35.45, '195270', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (261, 3, '[3]', 210, 'ot_300', '特立尼达和多巴哥', 'Trinidad And Tobago', 'TT', 'TeLiNiDaHeDuoBaGe', 'TLNDHDBG', 'TTO', '1809', 2, '-4', -61.31, -10.38, '555717', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (262, 1, '[1]', 210, 'ot_500', '土耳其', 'Turkey', 'TR', 'TuErQi', 'TEQ', 'TUR', '90', 1, '+3', 39.57, 32.54, '174737', 298795);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (263, 1, '[1]', 210, 'ot_500', '土库曼斯坦', 'Turkmenistan', 'TM', 'TuKuManSiTan', 'TKMST', 'TKM', '993', 1, '+5', 38, 57.5, '223026', 1218197);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (264, 5, '[5]', 210, 'ot_300', '突尼斯', 'Tunisia', 'TN', 'TuNiSi', 'TNS', 'TUN', '216', 2, '+1', 36.5, 10.11, '192757', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (265, 6, '[6]', 210, 'ot_500', '图瓦卢', 'Tuvalu', 'TV', 'TuWaLu', 'TWL', 'TUV', '688', 2, '+12', 8.31, 179.12, '2177266', 2110297);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (266, 6, '[6]', 210, 'ot_300', '瓦努阿图', 'Vanuatu', 'VU', 'WaNuATu', 'WNAT', 'VUT', '678', 2, '+11', 17.44, 168.19, '2177246', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (267, 3, '[3]', 210, 'ot_300', '危地马拉', 'Guatemala', 'GT', 'WeiDiMaLa', 'WDML', 'GTM', '502', 2, '-6', 14.4, -90.22, '1521463', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (268, 4, '[4]', 210, 'ot_600', '委内瑞拉', 'Venezuela', 'VE', 'WeiNeiRuiLa', 'WNRL', 'VEN', '58', 2, '-4', 10.3, -66.55, '272644', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (269, 1, '[1]', 210, 'ot_300', '文莱', 'Brunei', 'BN', 'WenLai', 'WL', 'BRN', '673', 1, '+8', 4.52, 115, '2103120', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (270, 5, '[5]', 210, 'ot_500', '乌干达', 'Uganda', 'UG', 'WuGanDa', 'WGD', 'UGA', '256', 2, '+3', 0.2, 32.3, '192796', 226074);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (271, 2, '[2]', 210, 'ot_300', '乌克兰', 'Ukraine', 'UA', 'WuKeLan', 'WKL', 'UKR', '380', 1, '+2', 50.3, 30.28, '60199', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (272, 4, '[4]', 210, 'ot_300', '乌拉圭', 'Uruguay', 'UY', 'WuLaGui', 'WLG', 'URY', '598', 2, '-3', -34.5, -56.11, '287072', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (273, 1, '[1]', 210, 'ot_300', '乌兹别克斯坦', 'Uzbekistan', 'UZ', 'WuZiBieKeSiTan', 'WZBKST', 'UZB', '233', 1, '+5', 41.2, 69.1, '196240', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (274, 2, '[2]', 210, 'ot_300', '西班牙', 'Spain', 'ES', 'XiBanYa', 'XBY', 'ESP', '34', 1, '+1', 40.25, -3.45, '1311341', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (275, 2, '[2]', 210, 'ot_300', '希腊', 'Greece', 'GR', 'XiLa', 'XL', 'GRC', '30', 1, '+2', 37.58, 23.46, '192307', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (276, 1, '[1]', 210, 'ot_300', '新加坡', 'Singapore', 'SG', 'XinJiaPo', 'XJP', 'SGP', '65', 1, '+8', 1.2904753, 103.8520359, '536780', 1880251);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (277, 6, '[6]', 210, 'ot_300', '新西兰', 'New Zealand', 'NZ', 'XinXiLan', 'XXL', 'NZL', '64', 2, '+12', -41.19, 174.46, '556706', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (278, 2, '[2]', 210, 'ot_500', '匈牙利', 'Hungary', 'HU', 'XiongYaLi', 'XYL', 'HUN', '36', 1, '+1', 47.29, 19.05, '21335', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (279, 1, '[1]', 210, 'ot_300', '叙利亚', 'Syria', 'SY', 'XuLiYa', 'XLY', 'SYR', '963', 1, '+2', 34.6401861, 39.0494106, '184840', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (280, 3, '[3]', 210, 'ot_600', '牙买加', 'Jamaica', 'JM', 'YaMaiJia', 'YMJ', 'JAM', '1876', 2, '-5', 18, -76.5, '555017', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (281, 1, '[1]', 210, 'ot_300', '亚美尼亚', 'Armenia', 'AM', 'YaMeiNiYa', 'YMNY', 'ARM', '374', 1, '+4', 40.1, 44.31, '364066', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (282, 1, '[1]', 210, 'ot_300', '也门', 'Yemen', 'YE', 'YeMen', 'YM', 'YEM', '967', 1, '+3', 16.3471243, 47.8915271, '305092', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (283, 2, '[2]', 210, 'ot_500', '意大利', 'Italy', 'IT', 'YiDaLi', 'YDL', 'ITA', '39', 1, '+1', 41.54, 12.29, '365331', 3175395);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (284, 1, '[1]', 210, 'ot_500', '伊拉克', 'Iraq', 'IQ', 'YiLaKe', 'YLK', 'IRQ', '964', 1, '+3', 33.2, 44.3, '304934', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (285, 1, '[1]', 210, 'ot_300', '伊朗', 'Iran', 'IR', 'YiLang', 'YL', 'IRN', '98', 1, '+3:30', 35.44, 51.3, '304938', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (286, 1, '[1]', 210, 'ot_500', '印度', 'India', 'IN', 'YinDu', 'YD', 'IND', '91', 2, '+3:30', 28.37, 77.13, '304716', 1269750);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (287, 1, '[1]', 210, 'ot_300', '印度尼西亚', 'Indonesia', 'ID', 'YinDuNiXiYa', 'YDNXY', 'IDN', '62', 2, '+7', -6.09, 106.49, '304751', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (288, 2, '[2]', 210, 'ot_300', '英国', 'United Kingdom', 'GB', 'YingGuo', 'YG', 'GBR', '44', 1, '+0', 51.36, -0.05, '62149', 2635167);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (289, 1, '[1]', 210, 'ot_500', '以色列', 'Israel', 'IL', 'YiSeLie', 'YSL', 'ISR', '972', 1, '+2', 31.47, 35.12, '1473946', 294640);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (290, 1, '[1]', 210, 'ot_500', '约旦', 'Jordan', 'JO', 'YueDan', 'YD', 'JOR', '962', 1, '+2', 31.57, 35.52, '184818', 248816);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (291, 1, '[1]', 210, 'ot_300', '越南', 'Vietnam', 'VN', 'YueNan', 'YN', 'VNM', '84', 2, '+7', 21.05, 105.55, '49915', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (292, 5, '[5]', 210, 'ot_500', '赞比亚', 'Zambia', 'ZM', 'ZanBiYa', 'ZBY', 'ZMB', '260', 2, '+2', -15.28, 28.16, '195271', 895949);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (293, 5, '[5]', 210, 'ot_300', '乍得', 'Chad', 'TD', 'ZhaDe', 'ZD', 'TCD', '235', 2, '+1', 12.1, 14.59, '2361304', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (294, 4, '[4]', 210, 'ot_300', '智利', 'Chile', 'CL', 'ZhiLi', 'ZL', 'CHL', '56', 2, '-4', -33.24, -70.4, '167454', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (295, 5, '[5]', 210, 'ot_300', '中非', 'Central African Republic', 'CF', 'ZhongFei', 'ZF', 'CAF', '236', 2, '+1', 4.23, 18.35, '192790', NULL);
INSERT INTO `country` (`id`, `parent_id`, `parent_path`, `level_type`, `next_level_type`, `name_cn`, `name_en`, `name_other`, `name_pinyin`, `name_jianpin`, `region_code`, `phone_code`, `zone`, `utc`, `lng`, `lat`, `osm_id`, `geo_names_id`) VALUES (296, 1, '[1]', 210, 'cn_300', '中国', 'China', 'CN', 'ZhongGuo', 'ZG', 'CHN', '86', 1, '+8', 39.55, 116.2, NULL, NULL);
